carlist/urls.py
from django.contrib import admin
from django.urls import path, include
from cars import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

cars/urls.py
from django.contrib import admin
from cars import views
from django.urls import path, include
from .views import CarList


cars_name = 'cars'
urlpatterns = [
    path('', CarList.as_view(), name='carlist'),
]

cars/models.py
from django.db import models

TRANSMISSION_CHOICES = (
	(1, 'механика'),
	(2, 'автомат'),
	(3, 'робот'),
)

class Car(models.Model):
	production = models.CharField(max_length=50)
	model = models.CharField(max_length=50)
	year = models.IntegerField()
	transmission = models.SmallIntegerField(choices=TRANSMISSION_CHOICES)
	color = models.CharField(max_length=20)

	def __str__(self):
		return self.production + ' ' + self.model + ' ' + str(self.year)

cars/forms.py
from django import forms
from .models import Car

cars/views.py
from django.db.models import Q
from django.views.generic import ListView
from .models import Car

import logging

logger = logging.getLogger(__name__)


class CarList(ListView):
    model = Car
    template_name = 'carlist.html'
    context_object_name = 'cars'

    def get_queryset(self):
        logger.debug(f"CarsList from user: {self.request.user.id} with params: {self.request.GET}")
        # logger.info("CarsList.get_queryset called")
        try:
            search_query = self.request.GET.get('search', '')
            qs = Car.objects.all()
            if search_query:
                qs = Car.objects.filter(Q(production__icontains=search_query)
                                        | Q(model__icontains=search_query)
                                        | Q(color__icontains=search_query)
                                        | Q(year__icontains=search_query)
                                        | Q(transmission__icontains=search_query))
            return qs
        except Exception as exc:
            logger.error(str(exc))
            raise

cars/templates/carlist.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock css %}
    {% if cars %}
    {% for car in cars %}
    <table border=1, class="table table-striped table-dark">
        <tr>
            <td style="width: 150px;"> {{ car.production }} </td>
            <td style="width: 150px;"> {{ car.model }} </td>
            <td style="width: 150px;"> {{ car.get_transmission_display }} </td>
            <td style="width: 150px;"> {{ car.color }} </td>
            <td style="width: 150px;"> {{ car.year }} </td>
        </tr>
    </table>
    {% endfor %}
    {% else %}
        <h2 style="display: flex; justify-content: center;">Нет таких автомобилей.</h2>
    {% endif %}
{% endblock content %}

cars/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cars Catalog</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700i&display=swap" rel="stylesheet">
    {% block css %}
    {% endblock css %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="{% url 'carlist' %}">Поиск</a>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Поиск авто" aria-label="Search" name="search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
          </form>
        </div>
      </nav>
      <h1 style="display: flex; justify-content: center;">Тут собрана информация о машинах наших посетителей</h1>
    {% block content %}

    {% endblock content %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>